### ISSUE TITLE
need to add link to SLD for each feature type version

### ISSUE THREAD

**Issue by smrgeoinfo** [usgin/modelmanager#2]
in the (JSON) versions: key, after the the field_info, need to add a key with a URL for a default SLD to use for the feature type

e.g. :  (new key is "default_sld")

{"versions": [
   {
     "field_info": [...],
     "uri": "http://schemas.usgin.org/uri-gin/ngds/dataschema/activefault/1.1",
     "xsd_file_path": "http://schemas.usgin.org/files/active-faultquaternary-fault/1.1/ActiveFault1.1.xsd",
     "version": "1.1",
     "xls_file_path": "http://schemas.usgin.org/files/active-faultquaternary-fault/1.1/ActiveFaultTemplate1.1.xls",
     "date_created": "2012-12-17",
     "sample_wfs_request": ""
     "default_sld": http://schemas.usgin.org/files/active-faultquaternary-fault/1.2/ActiveFaults.sld
},  ...

**Comment by rclark** [comment]
Done. See http://schemas.usgin.org/contentmodel/1.json
